CREATE TABLE IF NOT EXISTS sms_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempotency_key TEXT NOT NULL,
  to_phone TEXT NOT NULL,
  body TEXT NOT NULL,
  event_type TEXT NOT NULL DEFAULT 'transactional',
  booking_id BIGINT,
  recipient_type TEXT NOT NULL DEFAULT 'customer',
  status TEXT NOT NULL DEFAULT 'queued',
  twilio_sid TEXT,
  error_message TEXT,
  raw_response TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_sms_messages_idempotency_key
ON sms_messages(idempotency_key);

CREATE INDEX IF NOT EXISTS idx_sms_messages_booking_id
ON sms_messages(booking_id);

CREATE INDEX IF NOT EXISTS idx_sms_messages_status_created_at
ON sms_messages(status, created_at DESC);

ALTER TABLE sms_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS sms_messages_service_role_only ON sms_messages;

CREATE POLICY sms_messages_service_role_only ON sms_messages
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

-- Optional: Allow authenticated users to view their own SMS messages
-- Uncomment if you want customers to see their SMS history
-- CREATE POLICY sms_messages_user_read ON sms_messages
-- FOR SELECT
-- TO authenticated
-- USING (
--   to_phone IN (
--     SELECT phone FROM customer_profiles WHERE customer_user_id = auth.uid()::text
--   )
-- );
